server:
  port: 8080
spring:
  application:
    name: "Reportes"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
    active: local
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
aws:
  dynamodb:
    endpoint: "https://dynamodb.us-east-1.amazonaws.com"
  region: us-east-1

adapter:
  sqs:
    region: "us-east-1"
    queueUrl: "https://sqs.us-east-1.amazonaws.com/326623589662/reporte-sqs"

